SEARCH_DIR(.\)
SEARCH_DIR(d:\dev-pas\units\)
SEARCH_DIR(d:\dev-pas\units\rtl\)
SEARCH_DIR(d:\dev-pas\bin\)
INPUT(
d:\dev-pas\units\rtl\wprt0.ow
d:\documentos\nacho\fod\archivos\practica1\ej5\ej5p1.ow
)
GROUP(
d:\dev-pas\units\rtl\libpobjpas.aw
d:\dev-pas\units\rtl\libpsyswin32.aw
)
